package com.wellness.wellnessappbackend.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    MALFORMED_JSON,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    EMAIL_ALREADY_EXISTS,
    WELLNESS_LOG_ALREADY_EXISTS,
    RESOURCE_NOT_FOUND,
    INVALID_DATE_RANGE,
    NO_AI_ADVICE_FOUND,
    AI_SERVICE_UNAVAILABLE,
    RATE_LIMIT_EXCEEDED,
    UNSUPPORTED_MEDIA_TYPE,
    METHOD_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR
}
